dist: trusty
sudo: no

language: python

addons:
  postgresql: "11"
  apt:
    packages:
      - postgresql-11-postgis-2.5

cache: pip

services:
  - redis-server

env:
  - TOXENV=flake8
  - TOXENV=isort

matrix:
  fast_finish: true
  include:
    - python: 3.8
      env: TOXENV=py38-2.2-sqlite
    - python: 3.8
      env: TOXENV=py38-2.2-postgresql
    - python: 3.8
      env: TOXENV=py38-2.2-postgis
    - python: 3.8
      env: TOXENV=py38-3.0-sqlite
    - python: 3.8
      env: TOXENV=py38-3.0-postgresql
    - python: 3.8
      env: TOXENV=py38-3.0-postgis
    - python: 3.8
      env: TOXENV=py38-3.1-sqlite
    - python: 3.8
      env: TOXENV=py38-3.1-postgresql
    - python: 3.8
      env: TOXENV=py38-3.1-postgis
    - python: 3.8
      env: TOXENV=py38-master-sqlite
    - python: 3.8
      env: TOXENV=py38-master-postgresql
    - python: 3.8
      env: TOXENV=py38-master-postgis
  allow_failures:
    - env: TOXENV=py38-master-sqlite
    - env: TOXENV=py38-master-postgresql
    - env: TOXENV=py38-master-postgis

install:
  - pip install tox coveralls

before_script:
  - if echo $TOXENV | grep -E '(-postgresql|-postgis)' -q; then psql -U postgres -c "CREATE DATABASE mutant;"; fi
  - if echo $TOXENV | grep '\-postgis' -q; then psql mutant -U postgres -c "CREATE EXTENSION postgis; CREATE EXTENSION postgis_topology;"; fi

script:
  - tox

after_success:
  - coveralls
